name: Publish
on:
  push:
    tags:
      - v*
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v1
        with:
          path: .gradle
          key: ${{ runner.os }}-gradle-project-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle-project-
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Publish
        env:
          USERNAME: irgaly
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish
